service: linux-skills-lambda

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-2


functions:
  hello:
    handler: handler.question
    events:
      - http:
          path: question
          method: get
          cors: true
      - http:
          path: question
          method: post
          cors: true


plugins:
  - serverless-webpack


