service: linux-skills-lambda

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-2


functions:
  getquestion:
    handler: functions/getquestion.getquestion
    events:
      - http:
          path: question
          method: get
          cors: true
  answerquestion:
    handler: functions/answerquestion.answerquestion
    events:
      - http:
          path: question
          method: post
          cors: true


plugins:
  - serverless-webpack


